---
- hosts: all
  become: true
  tasks:

  - name: instaling neofetch
    ansible.builtin.apt:
      name: 
       - wget
       - neofetch
       - sl
      update_cache: yes
      state: latest


- hosts: web_server
  become: true
  tasks:

  - name: updating the cache
    ansible.builtin.apt:
      name:
       - wget
       - sl
      state: absent 
