---
- name: Initialize Kubernetes master
  ansible.builtin.command: kubeadm init --pod-network-cidr=10.244.0.0/16
  register: kubeadm_output
  ignore_errors: yes
- name: Set up kubectl for the current user
  ansible.builtin.command: "{{ item }}"
  with_items:
        - "mkdir -p $HOME/.kube"
        - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
        - "chown $(id -u):$(id -g) $HOME/.kube/config"
- name: Install Calico network plugin
  ansible.builtin.command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  when: "'calico' in kubeadm_output.stdout"
